#! /bin/bash
CSV=cases.csv;
CASES_ROW=5;
URL="https://www.health.govt.nz/our-work/diseases-and-conditions/covid-19-novel-coronavirus/covid-19-current-cases";

declare -a CITIES=(
  "Auckland" 
  "Nelson" 
  "Manawatu" 
  "Taupo" 
  "Wellington" 
  "Waikato"
  "Wairarapa" 
  "Invercargill" 
  "Hawkes\ Bay" 
  "Canterbury" 
  "Southern\ DHB" 
  "Rotorua" 
  "Northland" 
  "Taranaki" 
  "Dunedin"
  "Otago"
  "Bay\ of\ Plenty"
  "Hamilton"
  "Tasman"
  "Marlborough"
  "Upper\ Hutt"
  "Kapiti\ Coast"
);

# Fetch the and store its HTML 
curl -s $URL > data;

# Extract the data table and store it
< data tr -d '\n' | grep -oP '(?<=<table class="table-style-two").*?(?=</table>)' > out;

CASES=0;

# For each city:
#   count the number of cases
#   display the count 
#   update the csv 
#   update the total cases
for city in "${CITIES[@]}"
do 
  n=$(grep -o "<td>$city</td>" out | wc -l);
  m=$(grep -o "<td>$city&nbsp;</td>" out | wc -l); 
  c=$((n+m))
  printf "%s " $city;
  printf "%d\n" $c;
  sed -i "/^$city,/s/[^,]*/$c/$CASES_ROW" $CSV;
  CASES=$((CASES+c));
done 

printf "Total Cases: %d\n" $CASES;
