#! /bin/bash
CSV=cases.csv

URL="https://www.health.govt.nz/our-work/diseases-and-conditions/covid-19-novel-coronavirus/covid-19-current-cases";

declare -a CITIES=(
  "Auckland" 
  "Nelson" 
  "Manawatu" 
  "Taupo" 
  "Wellington" 
  "Waikato"
  "Wairarapa" 
  "Invercargill" 
  "Hawkes\ Bay" 
  "Canterbury" 
  "Southern\ DHB" 
  "Rotorua" 
  "Northland" 
  "Taranaki" 
  "Dunedin"
  "Otago"
  "Bay\ of\ Plenty"
  "Hamilton"
  "Tasman"
  "Marlborough"
);

curl -s $URL > data;
< data tr -d '\n' | grep -oP '(?<=<table class="table-style-two").*?(?=</table>)' > out;

CASES=0;

for city in "${CITIES[@]}"
do 
  n=$(grep -o "<td>$city</td>" out | wc -l);
  m=$(grep -o "<td>$city&nbsp;</td>" out | wc -l);
  CASES=$((CASES+n+m));
  printf "%s " $city;
  printf "%d\n" $((n+m));
  sed -i "/^$city,/s/[^,]*/$((n+m))/5" $CSV;
done 

printf "Total Cases: %d\n" $CASES;

